version: "3"
services:
  svr:
    stdin_open: true
    tty: true
    build:
      context: ./svr
      dockerfile: Dockerfile
    image: nsrllookup-svr
    volumes:
    - ./tests/hashes.txt:/usr/local/share/nsrlsvr/hashes.txt

  sut:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - svr
    command: sh -c "/wait && nosetests -w /api/tests --with-coverage --cover-package=."
    environment:
      - WAIT_HOSTS=svr:9120
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30