version: "3"
services:
  svr:
    build:
      context: ./svr
      dockerfile: Dockerfile
    image: nsrllookup-svr
    volumes:
      - ./nsrlsvr/hashes.txt:/usr/local/share/nsrlsvr/hashes.txt

  svr-prepare:
    build:
      context: ./svr
      dockerfile: Dockerfile
    image: nsrllookup-svr
    volumes:
      - ./nsrlsvr/:/usr/local/share/nsrlsvr/
    entrypoint: "/prepare-hash-set.sh"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - svr
    command: sh -c "/wait && python /api/app.py"
    environment:
      - WAIT_HOSTS=svr:9120
      - WAIT_HOSTS_TIMEOUT=600
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    ports:
      - 5000:5000