version: "3"
services:
  svr:
    image: cybagard/nsrllookup-svr:latest
    volumes:
      - ./nsrlsvr/:/usr/local/share/nsrlsvr/

  svr-prepare:
    image: cybagard/nsrllookup-svr:latest
    volumes:
      - ./nsrlsvr/:/usr/local/share/nsrlsvr/
    entrypoint: "/prepare-hash-set.sh"

  api:
    image: cybagard/nsrllookup-api:latest
    depends_on:
      - svr
    command: sh -c "/wait && python /api/app.py"
    environment:
      - WAIT_HOSTS=svr:9120
      - WAIT_HOSTS_TIMEOUT=600
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    ports:
      - 5000:5000