version: "3"
services:
  svr-test:
    build:
      context: ./svr
      dockerfile: Dockerfile
    image: nsrllookup-svr
    volumes:
      - ./api/tests/hashes.txt:/usr/local/share/nsrlsvr/hashes.txt

  svr:
    build:
      context: ./svr
      dockerfile: Dockerfile
    image: nsrllookup-svr
    volumes:
      - ./nsrlsvr/:/usr/local/share/nsrlsvr/

  svr-prepare:
    build:
      context: ./svr
      dockerfile: Dockerfile
    image: nsrllookup-svr
    volumes:
      - ./nsrlsvr/:/usr/local/share/nsrlsvr/
    entrypoint: "/prepare-hash-set.sh"

  api-test:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: nsrllookup-api
    depends_on:
      - svr-test
    command: sh -c "/wait && nosetests -w /api/tests --with-coverage --cover-package=."
    environment:
      - WAIT_HOSTS=svr-test:9120
      - WAIT_HOSTS_TIMEOUT=60
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=5
      - SERVER=svr-test

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: nsrllookup-api
    depends_on:
      - svr
    command: sh -c "/wait && python /api/app.py"
    environment:
      - WAIT_HOSTS=svr:9120
      - WAIT_HOSTS_TIMEOUT=600
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - SERVER=svr
    ports:
      - 5000:5000